export const SET_USERID = 'USER/set-userId'

export const GET_CLASS = 'FOOD/get-class'
export const GET_LIST = 'FOOD/get-list'
export const GET_MORE_LIST = 'FOOD/get-more-list'
export const GET_ELEMENT_CLASS = 'FOOD/get-element-class'
export const GET_ELEMENT = 'FOOD/get-element'
export const GET_FOOD_INFO = 'FOOD/get-foodinfo'
export const SET_ELEMENT_CLASS_STATUS = 'FOOD/SET_ELEMENT_CLASS_STATUS'
export const SET_TAB_DATA = 'FOOD/set-tab-data'