export const SET_USERID = 'USER/set-userId'

export const SET_CURRENT = 'FOOD/SET_CURRENT'
export const GET_CLASS = 'FOOD/get-class'
export const GET_LIST = 'FOOD/get-list'
export const GET_MORE_LIST = 'FOOD/get-more-list'
export const GET_ELEMENT_CLASS = 'FOOD/get-element-class'
export const GET_ELEMENT = 'FOOD/get-element'
export const GET_FOOD_INFO = 'FOOD/get-foodinfo'
export const SET_ELEMENT_CLASS_STATUS = 'FOOD/SET_ELEMENT_CLASS_STATUS'
export const SET_TAB_DATA = 'FOOD/set-tab-data'
export const SET_FOOD_COOD = 'FOOD/SET_FOOD_COOD'
export const GET_FOOD_ALL_LIST = 'FOOD/GET_FOOD_ALL_LIST'
export const SET_SELECTED_FOOD = 'FOOD/SET_SELECTED_FOOD'
export const DELETE_SELECTED_FOOD = 'FOOD/DELETE_SELECTED_FOOD'
export const SET_SELECTED_ELEMENT = 'FOOD/SET_SELECTED_ELEMENT'
export const DELETE_SELECTED_ELEMENT = 'FOOD/DELETE_SELECTED_ELEMENT'
export const SET_TABLE_DATA = 'FOOD/SET_TABLE_DATA'

export const HISTOTY_LIST = 'TOOL/HISTOTY_LIST'
export const LIST_OPEN = 'TOOL/LIST_OPEN'
export const DETELE_LIST_ITEM = 'TOOL/DETELE_LIST_ITEM'
